name = "HigherOrderClustering"
uuid = "751bb2a0-4d61-58a3-b68f-7f19cb6f620a"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
MatrixNetworks = "4f449596-a032-5618-b826-5a251cb6dc11"

[compat]
julia = "â‰¥ 0.6.0"
